### ISSUE TITLE
JS client may not give an error if sending an HTTP request fails

### ISSUE THREAD

**Issue by moozzyk** [AndrewBoklashko/SignalRReactNativeChat#1]
See: https://github.com/aspnet/SignalR/issues/957#issuecomment-333652247

In ReactNative the client was not able to connect to the server at all and the Error message was empty because both `status` and `statusCode` was `undefined`. It appears however that XmlHttpRequest contains a useful error message which we should include in the Error.

**Comment by AndrewBoklashko** [comment]
Did you mean to create it here: https://github.com/aspnet/SignalR/issues ?

**Comment by moozzyk** [comment]
LOL yes. Wrong tab.
